name: ServiceJi
description: Service provider company.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 3.0.10
  connectivity: ^0.4.9+2
  nb_utils:  3.2.9
  dots_indicator: ^0.0.4
  google_fonts: 1.0.0
  http: 0.12.0+4
  dotted_border: 1.0.5
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  url_launcher: ^5.4.2
  percent_indicator: ^2.1.5
  flutter_rating_bar: 3.0.1+1
 # intl: 0.16.1
  intl: 0.17.0-nullsafety.2
  image_picker: 0.6.4
  share: 0.6.3+6
  carousel_pro: 1.0.0
  package_info: 0.4.0+16
  photo_view: 0.9.2
  html: 0.14.0+3
  webview_flutter: 0.3.22+1
  flutter_staggered_grid_view: 0.3.0
  cached_network_image: ^2.3.2+1
  lottie: ^0.6.0
  flutter_localizations:
    sdk: flutter
  provider: 4.0.4
  flutter_speed_dial: ^1.2.5
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  #flutter_crashlytics:
  #firebase_crashlytics: 0.1.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  onesignal_flutter: ^2.6.1
  mobx_codegen:
  build_runner: ^1.9.0
  #flutter packages pub run build_runner build

flutter:

  uses-material-design: true

  assets:
    - images/serviceji/
    - lang/en.json
    - lang/fr.json
    - lang/es.json
    - lang/af.json
    - lang/de.json
    - lang/in.json
    - lang/vi.json
    - lang/tr.json
    - lang/hi.json
    - lang/ar.json
    - assets/

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/Jost-Regular.ttf
        - asset: fonts/Jost-Medium.ttf
        - asset: fonts/Jost-Bold.ttf
        - asset: fonts/Jost-SemiBold.ttf

